### PR TITLE
raise exception after exiting watcher.each

### LINKED ISSUE #213: High request rate towards Kubernetes API server
After upgrading to 2.4.2 I observed high request rate towards our Kubernetes API server.

I believe the reason is the code introduced in #204 

We got the following response for the pod event watch:
```
{"type":"ERROR","object":{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"too old resource version: 201394728 (201675730)","reason":"Gone","code":410}}
```
In this case the connection was closed and no exception raised, therefor the code setting pod_watch back to nil and doing the exponential backoff did not get executed, but instead the thread kept retrying with this old resource version in an endless loop.

I think either type = ERROR case should be handled in the watch.each block here:
https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb#L104

or just outside of the watch.each block an exception should be raised to make sure the rescue block gets executed.

What do you think @qingling128 ?

### PR DESCRIPTION
**Pull request by mszabo**
fixes #213

### CODE REVIEW

File: lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb [hunk 1]
```diff
@@ -119,6 +119,7 @@ def process_namespace_watcher_notices(watcher)
             @stats.bump(:namespace_cache_watch_ignored)
         end
       end
+      raise
```
Comment (jcantrill) [inline lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb]: Won't this simply fall through all the time and raise an exception on every notification.  Should we be evaluating for a specific `notice.type` or at least have `continue` statements above

Comment (jcantrill) [reply lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb]: as i suspected:
```
Error: test: pod MODIFIED cached when hostname matches(DefaultPodWatchStrategyTest)
: RuntimeError: 
/home/circleci/fluent-plugin-kubernetes_metadata_filter/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:128:in `process_pod_watcher_notices'
/home/circleci/fluen
```

Comment (jcantrill) [reply lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb]: its probably something more like:
```
when 'ERROR':
  message = notice['object']['message'] if notice['object'] && notice['object']['message'
  raise "Error while watching namespaces: #{message}"
```

Comment (mszabo) [reply lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb]: I was thinking about doing it with when 'ERROR', but then it can still exit the watcher.each block without an exception which can cause endless loop without backoff.

I don't know how this testing framework works, but in reality it stays inside the watcher.each block until the connection is open. Watching opens long running connections, the API server usually kills the connection after 40-50 minutes.

Comment (qingling128) [reply lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb]: Hmm... I thought the `notice.type` value can only be one of these there: `ADDED`, `MODIFIED`, `DELETED`.

Reference: https://github.com/abonas/kubeclient/blame/28dfc4d538d72127015dc9b90e6b776c4b0fb986/test/test_watch.rb#L8

@jcantrill 's suggestion in https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/214/files#r384729998 makes sense to me.

Looking at the issue reported at https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/issues/213#issue-571115649, it's not an unexpected exception. Besides, if an exception if thrown, https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/9b48b09fa56fcb32c0bcc8e7547bb7589a309125/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb#L42 should have caught it.

Comment (mszabo) [reply lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb]: There is no exception thrown when the connection is closed.

When you open the HTTP connection for the watcher you get a 200 OK reply from the server, but connection stays open and it is streaming the events over the same connection. Kubernetes will close it after around 1 hour (at least on our cluster).

Once it's closed there is no exception, it's finishing normally.

So the  [thread loop](https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/blob/master/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb#L39) will execute, but because there were no exception the rescue block did not execute and nothing set the pod_watcher to nil. It will use resource_version from the first run.
Kubernetes API remembers old resources for a while, but after some time it will return ERROR with "too old resource version" message and closes the connection (no exception happens).

When this happens the thread loop will start the watcher again with the old resource version, gets error again and this continues in a loop. It results in a high load on the API server and no way to recover except restarting fluentd.

I can rework this PR to use the when 'ERROR' case, but then the issue can still happen if the connection is closed by the API server without returning ERROR and throwing exception.

I think an exception should be raised whenever the watcher.each block is exited, because it means the long-running connection was closed gracefully.
Unfortunately I am not sure how I can make it work with the tests.

Comment (qingling128) [reply lib/fluent/plugin/kubernetes_metadata_watch_namespaces.rb]: Re https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/214#discussion_r384826454: Ah I see. That sounds good to me. Instead of a simple `raise`, can we give it some message to help with debugging / trouble shooting when the issue happens?

For the fact that it returned `ERROR` notice, seems like there is some discussion at [kubeclient/pull/275](https://github.com/abonas/kubeclient/pull/275#issuecomment-591928097). Sounds like it might be fixed in

**Comment by qingling128** [comment]
Perhaps we can get this fix merged the way it is right now to handle the `ERROR` type of notice and iterate on it later once the dust settles for https://github.com/abonas/kubeclient/pull/275?

**Comment by mszabo** [comment]
@qingling128 Iooking at the code again, I think Thread.current[:pod_watch_retry_count] should be reset when non-error events are received otherwise that counter will just keep increasing whenever the API server respons 410 Gone and after couple of iterations the code will raise Fluent::UnrecoverableError. What do you think?

**Comment by qingling128** [comment]
@mszabo - Good point. What do you think about resetting it to 0 in the `get_pods_and_start_watcher` method instead of every non-error events? That way if the events are a mix of good ones and bad ones, we can still guarantee we will eventually still restart.

**Comment by mszabo** [comment]
@qingling128 sounds good. I tried to add it after the resourceVersion successfully queried from the API server, but it makes the "pod watch retries when exceptions are encountered" test hang forever and I am not sure how to fix the test

**Comment by qingling128** [comment]
@mszabo - Interesting. I took a closer look. This (https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/215/files) seems to work and should be equivalent. Also, now I think about it, once an `Exception` is raised, Fluentd will restart, which resets the variable anyway. So the change is probably not needed in the first place.

BTW, I'm not entirely sure why the test failed in the other approach. I guess it might be related to how the stubs work or something.

**Comment by jcantrill** [comment]
@mszabo can you post unit test results until we can properly fix up the CI?

**Comment by qingling128** [comment]
I could view the test results in this PR. Quoted below:

```
!/bin/bash -eo pipefail
bundle exec rake test
Run options: --seed 21318

# Running tests:



Finished tests in 0.000154s, 0.0000 tests/s, 0.0000 assertions/s.

0 tests, 0 assertions, 0 failures, 0 errors, 0 skips
Loaded suite /home/circleci/fluent-plugin-kubernetes_metadata_filter/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/lib/rake/rake_test_loader
Started
...................................................rake aborted!
Interrupt: 
/home/circleci/fluent-plugin-kubernetes_metadata_filter/vendor/bundle/ruby/2.4.0/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/usr/local/bundle/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/local/bundle/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/local/bundle/bin/bundle:23:in `load'
/usr/local/bundle/bin/bundle:23:in `<main>'
Tasks: TOP => test => base_test
(See full trace by running task with --trace)
F
===============================================================================
Failure: test: pod watch retries when exceptions are encountered(DefaultPodWatchStrategyTest)
/home/circleci/fluent-plugin-kubernetes_metadata_filter/test/plugin/test_watch_pods.rb:216:in `block (3 levels) in <class:DefaultPodWatchStrategyTest>'
     213:     test 'pod watch retries when exceptions are encountered' do
     214:       @client.stub :get_pods, @initial do
     215:         @client.stub :watch_pods, [[@created, @exception_raised]] do
  => 216:           assert_raise Fluent::UnrecoverableError do
     217:             set_up_pod_thread
     218:           end
     219:           assert_equal(3, @stats[:pod_watch_failures])
/home/circleci/fluent-plugin-kubernetes_metadata_filter/vendor/bundle/ruby/2.4.0/gems/minitest-4.7.5/lib/minitest/mock.rb:187:in `stub'
/home/circleci/fluent-plugin-kubernetes_metadata_filter/test/plugin/test_watch_pods.rb:215:in `block (2 levels) in <class:DefaultPodWatchStrategyTest>'
/home/circleci/fluent-plugin-kubernetes_metadata_filter/vendor/bundle/ruby/2.4.0/gems/minitest-4.7.5/lib/minitest/mock.rb:187:in `stub'
/home/circleci/fluent-plugin-kubernetes_metadata_filter/test/plugin/test_watch_pods.rb:214:in `block in <class:DefaultPodWatchStrategyTest>'

<Fluent::UnrecoverableError> expected but was
<SignalException(<SIGHUP>)>

diff:
? F    lu  e    nt::   UnrecoverableError
? Signa Exc ptio (<SIGH P>)              
===============================================================================
.....
Too long with no output (exceeded 10m0s): context deadline exceeded
```

I was able to reproduce the error above locally. The tests simply hang indefinitely until I manually killed it.

BTW, CI seems fixed already (at least it's passing for the `master` branch when I tried it). The experiment PR I tried also passed: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/215.

**Comment by mszabo** [comment]
> @mszabo - Interesting. I took a closer look. This (https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/215/files) seems to work and should be equivalent. Also, now I think about it, once an `Exception` is raised, Fluentd will restart, which resets the variable anyway. So the change is probably not needed in the first place.

@qingling128 I don't think #215 is equivalent. As you said, `Fluent::UnrecoverableError` will restart the process and the variable will reset, so no point resetting the variable just before throwing `Fluent::UnrecoverableError`. The original problem is that the Kubernetes API server will send `410 Gone` ERROR (note: 410 is not a HTTP response code here) every 40-50 minutes, it's handled in this PR by raising an exception and this exception is caught and the retry is executed (new resourceVersion polled from the API server). If the retry counter is never reset, after 10 `410 Gone` messages we will get a `Fluent::UnrecoverableError` and a process restart even though it's unnecessary. So I think the right place to reset the retry counter is after the new resourceVersion is successfully queried from the API server. I believe because the test always return a mocked resourceVersion it will get into an endless loop, but in reality when a new resourceVersion is returned the watch should continue from there like an endless loop, so this is normal. Just not sure how to fix the test. `Fluent::UnrecoverableError` should only be seen when the API server is unavailable for long enough time to fail all the retries.

**Comment by qingling128** [comment]
@mszabo - Ah, so it sounds like `410 Gone ERROR` is a recoverable error? I thought it's not recoverable error. If it's recoverable, we can do https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/215/commits/1382745a1860a672ea8f053f16e1b7753398a8e7 instead.

**Comment by mszabo** [comment]
@qingling128 yes, it's recoverable, just need to refresh the resourceVersion. The commit you mentioned also could help the situation, but get_pods_and_start_watcher is a better place to reset the counter in my opinion. I think the test is wrong here. Anyway, I am also happy with https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/commit/1382745a1860a672ea8f053f16e1b7753398a8e7 as well and the tests can stay as is with it.

**Comment by mszabo** [comment]
I removed the counter resets from this PR as it is handled in https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/commit/1382745a1860a672ea8f053f16e1b7753398a8e7

**Comment by qingling128** [comment]
FYI, I set up some experiments that ran overnight, and verified that the latest commit (which includes this fix) has better performance than `2.4.4`.

**The two commit hashes of the branches in comparison**

Commit hash of `lingshi-2-4--4` branch:
```
lingshi@lingshi-dev:~/repo/fluent-plugin-kubernetes_metadata_filter$ git log -n 1
commit 70e2a15873153c1130a4e49e52c971138dbf7cf8 (HEAD -> lingshi-2-4--4, tag: v2.4.4, origin/lingshi-2-4--4)
Author: Jeff Cantrill <jcantril@redhat.com>
Date:   Thu Mar 12 16:47:29 2020 -0400

    v2.4.4
```

Commit hash of `lingshi-add-pod-ip` branch:
```
$ git log -n 1
commit d3832d32425a4fb4cf9f0158f39e0e0d79930f33 (HEAD -> lingshi-add-pod-ip, origin/lingshi-add-pod-ip)
Author: Maxim Makarov <m@csgo.com>
Date:   Fri Mar 20 17:47:53 2020 +0300

    Add pod IP to kubernetes metadata (#218)

    * Add pod IP to kubernetes metadata
```

**CPU comparison**
image

**Memory comparison**
image

**Fluentd log entry processing capability comparison**
image

**Retries still works**
image

**No container restarts**
image

Thanks @mszabo and @jcantrill !

One thing I noticed is that `pod_watch_retry_backoff_interval` did not get reset to 0 once the retry succeeded (not related to this PR), and I sent a fix: https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/219

**Comment by jcantrill** [comment]
@qingling128 great work!

**Comment by qingling128** [comment]
Thank **you**!

I've verified the performance again as shown below after https://github.com/fabric8io/fluent-plugin-kubernetes_metadata_filter/pull/219 got merged.

`lingshi-70e2a1-244` is the 2.4.4 hash. `lingshi-faff00` is the latest hash in the master branch.

**CPU**
image

**memory**
image

**log throughput**
image

**retries are functional**
image

@jcantrill - Now that it looks all good, could you help create a new release when you get a sec?
