### PR TITLE
Reset watch retry count on successful connection to API Server

### LINKED ISSUE #249: fail to parse watch call response and crashes pod.
```
2020-08-28 15:36:27 +0000 [error]: Exception encountered parsing pod watch event. The connection might have been closed. Retried 10 times yet still failing. Restarting.error reading from socket: Could not parse data
#<Thread:0x0000562808f18f70@/usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.5.2/lib/fluent/plugin/filter_kubernetes_metadata.rb:276 run> terminated with exception (report_on_exception is true):
/usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.5.2/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:71:in `rescue in set_up_pod_thread': Exception encountered parsing pod watch event. The connection might have been closed. Retried 10 times yet still failing. Restarting. (Fluent::UnrecoverableError)
	from /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.5.2/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:40:in `set_up_pod_thread'
	from /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.5.2/lib/fluent/plugin/filter_kubernetes_metadata.rb:276:in `block in configure'
Unexpected error Exception encountered parsing pod watch event. The connection might have been closed. Retried 10 times yet still failing. Restarting.
  /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.5.2/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:71:in `rescue in set_up_pod_thread'
  /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.5.2/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:40:in `set_up_pod_thread'
  /usr/share/gems/gems/fluent-plugin-kubernetes_metadata_filter-2.5.2/lib/fluent/plugin/filter_kubernetes_metadata.rb:276:in `block in configure'

```
it is deployed on oracle cloud kubernetes. 
this plugin version 2.5.2

### PR DESCRIPTION
**Pull request by astencel-sumo**
Fixes #249.
 
This pull request adds resetting of pod and namespace watch retry count after successfully re-establishing connection to Kubernetes API server. This is to prevent Fluentd restarts in the following scenario (describing pod watch, but namespace watch works in the same way):

1. Pod watch connection to Kubernetes API server is successfully created by this plugin.
2. The pod watch connection is dropped by Kubernetes API server after certain period of time (API server is known to drop these connection every now and then, e.g. after 45 minutes or so).
3. The pod watch connection is successfully renewed by this plugin.
4. The above points 2-3 repeat more than `:watch_retry_max_times` with no watch updates coming from API server in the meantime, which would reset the watch retry count.

Nothing incorrect is actually happening in the above scenario, so we don't want to raise a `Fluent::UnrecoverableError` in such case (which causes the whole Fluentd instance to restart). To prevent raising the `Fluent::UnrecoverableError`, I propose to reset the watch retry count not only on receiving an update from the watch (which might not happen given for example no changes in the namespaces of the k8s cluster for a long time), but also on successful re-connection to the API server.

### CODE REVIEW

**Comment by jcantrill** [comment]
@jkohen @grosser might I get you to weigh in on these changes?

**Review by grosser — APPROVED** [review]

**Comment by jkohen** [comment]
@qingling128 FYI.

File: test/plugin/test_watch_pods.rb [hunk 1]
```diff
@@ -234,30 +234,37 @@ class DefaultPodWatchStrategyTest < WatchTest
       end
     end
 
-    test 'pod watch retries when exceptions are encountered' do
+    test 'pod watch resets watch retry count when exceptions are encountered and connection to k8s API server is re-established' do
```
Comment (qingling128) [inline test/plugin/test_watch_pods.rb:237]: Can we make this a new test and keep the old test that verifies the retry scenario?

Comment (astencel-sumo) [reply test/plugin/test_watch_pods.rb:253]: You're right @qingling128 , there were no tests for raising the `Fluent::UnrecoverableError` after my changes. I wasn't sure how to write such a test with the `minitest`'s stubs, but I think I got it to work using the stubs from `rr`.

Please let me know what you think.

Comment (qingling128) [reply test/plugin/test_watch_pods.rb:253]: Thanks. That looks good to me.

**Review by qingling128 — APPROVED** [review]

**Comment by astencel-sumo** [comment]
Thanks a lot for the reviews folks. Can we have this merged and released as new version?

**Comment by astencel-sumo** [comment]
Hey @jcantrill is there anything stopping us from merging and releasing a new version? Is there anything I could help with?

**Comment by djj0809** [comment]
@jcantrill our production fluentd instances are keeping restarting all the time, can we merge this and release a new version ASAP?

**Comment by frankreno** [comment]
@jcantrill @grosser @qingling128 - Is there any ETA on when this fix will be merged and a new release containing the fix available? We have numerous customers affected by this and waiting on this fix which is why @astencel-sumo helped address this.

**Comment by elsesiy** [comment]
Any progress on this?

**Comment by djj0809** [comment]
@jcantrill @grosser @qingling128  please merge it and release ASAP, it's really a annoying issue.

**Comment by grosser** [comment]
I can't merge/am not a maintainer 🤷 
also using [fluent-plugin-kubelet_metadata](https://github.com/grosser/fluent-plugin-kubelet_metadata) now if that is any help

**Comment by qingling128** [comment]
Same here. I think @jcantrill has merge access.

**Comment by jcantrill** [comment]
Sorry for the delay here.  I will release something shortly

**Comment by jcantrill** [comment]
published 2.5.3 https://rubygems.org/gems/fluent-plugin-kubernetes_metadata_filter/versions/2.5.3
